language: python
python: '2.7'
sudo: false
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
notifications:
  slack:
    rooms:
      secure: fjWayANYpBPrwsIwZ6cL7dzzCWGw5E3VhXbrJRiStX6NMb54dAZlwRDfZPO5WX48gS7HPCxEZ9vnWMPJ5Z+46ecZ/Rln0lJLPJvcimyPnGan1ZSL7nIkXuXUk8MGI49m7f16hGOrHWC04tqytIrv0AfFhg9LV6LIrPVNDe9GrQqsIUT8F53H5QN5VzZkkaV3K7rbeL0x5FxLKx3SjyvjRXpAVU/UiNT7OTsfgSwfn9mw8Qk1dh+iDE11OToBOyeSJyuRcv0Lu+R3xP3jyLywfg3lRz21H7Y3hkWgPu9hPChd/VunCCHVaLigphYLRdTInoN4ZQHcuUEdiFRMRdCNdNVOwXWUDFnGf47PA/NqTsDvnuG5WAG19wX6pa724CZRvYohI/KH9/08OcGEdkCthnP1fa3h1yKspbbEJ8JIpPO22x94PPJ3HGHSLMUy69T9MNwx5U/przPjEhL8lRk07fybM9BHGP20WbYMsPW0s+nDMbdBiJVoLVV5CkbnPS1Vu5yPyRZ5MnKK4E1ba662K9IlPDHoxImXiukpS0b9qux9j9KakIb6itjEX4hnluGUjSUhyH3bac+0ehUaFhAS3rKYQkVYtJ0BFhPOA7LmQnclTlExU7UlgSnAt7o4hvweBEIm15wp3frgKJyW8fFp5dQDQp0CDX9bw5J4GfyM1oU=
