---
- name: apt update and install https apt
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - libssl-dev
    update_cache: yes

- name: add apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: add mongo repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
    state: present

- name: apt install mongodb
  apt:
    name:
      - mongodb-org
    update_cache: yes

- name: mongodb start and enable
  systemd:
    daemon_reload: true
    name: mongod
    enabled: true
    state: started
