---
dependency:
  name: galaxy
driver:
  name: docker
  # name: vagrant
  # provider:
  #   name: virtualbox
# lint:
#   name: yamllint
# platforms:
#   - name: instance
#     box: ubuntu/xenial64
platforms:
  - name: instance
    image: ubuntu:16.04
    # privileged: true
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:rw
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # # command: /sbin/init
    # capabilities:
    #   - SYS_ADMIN
    # # exposed_ports:
    # #   - 80/udp
    # #   - 80/tcp
    # # published_ports:
    # #   - 0.0.0.0:8888:80/udp
    # #   - 0.0.0.0:8888:80/tcp
    # # groups:
    # #   - debian
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    # - destroy
    # - dependency
    # - syntax
    # - create
    # - prepare
    # - converge
    # - idempotence
    # - side_effect
    # - verify
    # - destroy